# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduzione alla programmazione per le scuole superiori
author: basics
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Basics2022/bbooks-programming-hs  # Online location of your book
  path_to_book: .                                           # Optional path to your book, relative to the repository root
  branch: master                                            # Which branch of the repository should be used when creating links (optional)

jupyter_cache: true             # Enable jupyter-cache for caching notebook outputs
exectue:
  cache: true                   # Allow Jupyter Book to store the outputs of executed cells
  execute_notebooks: auto       # Only execute notebooks that have changed 

launch_buttons:
  colab_url: "https://colab.research.google.com"    # colab
# notebook_interface: "classic"                     # jupyterlab

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

# sphinx extensions
sphinx:
  config:
    language: it
    html_theme_options:
      logo:
        image_light: logo.svg
        image_dark: logo-dark.svg
      repository_url: https://github.com/Basics2022/bbooks-physics-hs  # Online location of your book
      repository_branch: master
      use_repository_button: True
      use_edit_page_button: True
      use_issues_button: True
      launch_buttons:
        colab_url: "https://colab.research.google.com"    # colab
    html_favicon: favicon.svg
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    # - sphinx_togglebutton   # to be installed


